#server:
#  port: 8080
#spring:
#  profiles:
#    active: prod
#---
#server:
#  port: 8082
#spring:
#  profiles: dev
#---
#
#server:
#  port: 8087
#spring:
#  profiles: prod
#---
#person:
#  last-name: zhangsan
#  age: 18
#  boss: false
#  birth: 1994/06/14
#  maps: {k1: v1,k2: 12}
#  lists:
#    - shen
#    - bo
#  dog:
#    name: "萨达"
#    age: 11


